[2025-02-19T16:23:09.751+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T16:23:09.767+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_dag.transform_file manual__2025-02-19T16:23:03.518236+00:00 [queued]>
[2025-02-19T16:23:09.775+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_dag.transform_file manual__2025-02-19T16:23:03.518236+00:00 [queued]>
[2025-02-19T16:23:09.775+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-19T16:23:09.786+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_file> on 2025-02-19 16:23:03.518236+00:00
[2025-02-19T16:23:09.794+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T16:23:09.795+0000] {standard_task_runner.py:72} INFO - Started process 1226 to run task
[2025-02-19T16:23:09.795+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'covid_dag', 'transform_file', 'manual__2025-02-19T16:23:03.518236+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/covid_dag.py', '--cfg-path', '/tmp/tmp15iex47t']
[2025-02-19T16:23:09.797+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask transform_file
[2025-02-19T16:23:09.830+0000] {task_command.py:467} INFO - Running <TaskInstance: covid_dag.transform_file manual__2025-02-19T16:23:03.518236+00:00 [running]> on host 539a2c5d6322
[2025-02-19T16:23:09.895+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_dag' AIRFLOW_CTX_TASK_ID='transform_file' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T16:23:03.518236+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T16:23:03.518236+00:00'
[2025-02-19T16:23:09.896+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-19T16:23:12.043+0000] {covid_dag.py:22} INFO - Data saved in hospitalisation.csv ðŸ¥³
[2025-02-19T16:23:12.768+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/covid_dag.py", line 25, in transform
    plt.savefig('/./data/hospitalisation.png')
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/pyplot.py", line 1243, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/figure.py", line 3490, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2184, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2040, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py", line 481, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py", line 430, in _print_pil
    mpl.image.imsave(
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/image.py", line 1634, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 2591, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/./data/hospitalisation.png'
[2025-02-19T16:23:12.780+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=covid_dag, task_id=transform_file, run_id=manual__2025-02-19T16:23:03.518236+00:00, execution_date=20250219T162303, start_date=20250219T162309, end_date=20250219T162312
[2025-02-19T16:23:12.804+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-19T16:23:12.805+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task transform_file ([Errno 2] No such file or directory: '/./data/hospitalisation.png'; 1226)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/covid_dag.py", line 25, in transform
    plt.savefig('/./data/hospitalisation.png')
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/pyplot.py", line 1243, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/figure.py", line 3490, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2184, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2040, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py", line 481, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py", line 430, in _print_pil
    mpl.image.imsave(
  File "/home/airflow/.local/lib/python3.12/site-packages/matplotlib/image.py", line 1634, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 2591, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/./data/hospitalisation.png'
[2025-02-19T16:23:12.858+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-19T16:23:12.871+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T16:23:12.875+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
